title: Overseas Funeral Guide
description: A practical guide for handling post-death affairs abroad.
theme: jekyll-theme-cayman

# Navigation structure
# just-the-docs 的功能在这里没法完全用，但简单的导航还是支持的

just_the_docs:
  logo: false
  search_enabled: true
  aux_links:
    GitHub Repo: https://github.com/sliuxl/OverseasFuneralGuide

plugins:
  - jekyll-sitemap
